### ISSUE TITLE
allow version to be specified on command line and use non-custom kubernetes builds

### ISSUE THREAD

**Issue by djschny** [kubernetes-sigs/kubeadm-dind-cluster#19]
I noticed when going to use this, two things that concerned me:

* the kubernetes versions being used appear to be non-official versions
* when executing the scripts, then appear to hard code specific bugfix versions of kubernetes

I would expect the default behavior of the v1.6 script for example to use the latest bugfix version of v1.6. And optionally when starting up could override to use a different one.

**Comment by ivan4th** [comment]
The scripts use officially released binaries, see here: https://github.com/Mirantis/kubeadm-dind-cluster/blob/master/build/buildconf.sh
I try to update the config as new stable versions come out but frankly don't do it always in very timely manner -- will try to improve this.
As of specifying the version on command line instead of using the 'fixed' script, I have plans for this, but probably not right now.

**Comment by lukaszo** [comment]
As stated by Ivan, k-d-c uses latest available releases

**Comment by djschny** [comment]
I'm confused as to why this was closed? The following was stated as going to eventually be done:

> As of specifying the version on command line instead of using the 'fixed' script, I have plans for this, but probably not right now.

Shouldn't this stay open until it is done?

**Comment by pigmej** [comment]
It should be :)
