### ISSUE TITLE
DinDinD - Need way to configure NAT64 V4 Subnet without multicluster kicking in

### ISSUE THREAD

**Issue by leblancd** [kubernetes-sigs/kubeadm-dind-cluster#220]
For running K-D-C within a container (DinDinD configuration, as used in CI), we would like to have a way of specifying the NAT64 V4 subnet without having the scripts set up a cluster in multi-cluster mode. It would be better if the setting of NAT64 V4 subnet and the triggering of multi-cluster mode could be done independently.

Background:
When running K-D-C within a container (DinDinD configuration), we need a way of specifying the NAT64 V4 Subnet to be something different than the host Docker network (typically 172.17.0.0/16) and different than the container's base docker network (typically 172.18.0.0/16). For example, we'd like to set the K-D-C NAT64 V4 subnet to something like 172.20.0.0/16.

With the current K-D-C scripts, we would configure a NAT64 V4 subnet of 172.20.0.0/16 with the following environment variables:
    export NAT64_V4_SUBNET_PREFIX=172
    export CLUSTER_ID=20

The problem with this is that by specifying CLUSTER_ID, the K-D-C scripts automatically assume multi-cluster operation. For DinDinD, we don't need multi-cluster operation... the simpler non-multi-cluster operation would work fine in each individual DinDinD container.

For example, with the environment variables configured above, because multi-cluster mode is initiated, kubectl commands executed in the host DinDinD container *must* include a context:
```
root@d1c26b6ea88d:~/.kube# kubectl get pods
The connection to the server localhost:8080 was refused - did you specify the right host or port?
root@d1c26b6ea88d:~/.kube# kubectl --context dind-cluster-20 get pods
NAME                                             READY     STATUS    RESTARTS   AGE
kube-apiserver-kube-master-cluster-20            1/1       Running   1          2m
kube-controller-manager-kube-master-cluster-20   1/1       Running   0          2m
kube-scheduler-kube-master-cluster-20            1/1       Running   0          2m
root@d1c26b6ea88d:~/.kube# 
```
There may be other aspects of multi-cluster operation that are not desirable for DinDinD operation.

**Comment by pmichali** [comment]
For DinDinD you can use a cluster ID of zero, which means first cluster of a multi-cluster configuration or single cluster mode. You can omit the CLUSTER_ID and it will default to zero.

**Comment by pmichali** [comment]
From discussion with @leblancd, the NAT64 mapping network, should be in RFC-1418 private network range.  Currently, one can use a prefix of 10, and comply with that requirement, but we may want to consider using the 172.16.0.0/12 subnet and ensure addresses are within limits.

**Comment by pmichali** [comment]
Some options are:

Option A

User specifies a two octet NAT64 prefix, iff they want to override.  Default: 172.17. Subnet will be <PREFIX>.<PREFIX>.0.0/16 always.

Single cluster, no settings needed, get 172.17.0.0/16.
Single cluster that needs special subnet, set NAT64_V4_SUBNET_PREFIX=172.20, for example.

Multicluster, for all but the first cluster (as long as no docker conflict), user sets NAT64_V4_SUBNET_PREFIX=172.X, where X is unique and between 17..31 and doesn’t conflict with docker.

Advantages: Can use any prefix (e.g. 10.50).
Disadvantages: For multi-cluster, must specify this, along with CLUSTER_ID, for all but first cluster.


Option B

User specifies two octet NAT64 prefix, with default 172.17. Subnet will be <PREFIX>.<PREFIX+CLUSTER_ID>.0.0/16

Single cluster, no settings needed, get 172.17.0.0/16.
Single cluster that needs special subnet, set NAT64_V4_SUBNET_PREFIX=172.20, for example.

Multicluster, if use 172.X as prefix, X must be between 17..31 and doesn’t conflict with docker. In addition, CLUSTER_ID must be 0..(31-X), so that it stays within limits of private network. If use 10.X, just need cluster ID 0..(254-X).

Advantages: Don’t need to specify, unless have a docker issue.
Disadvantages: Applies some limits on CLUSTER_ID and the limits differ based on 172.x or 10.y used for prefix.


Option C

User specifies one octet NAT64 base, between 17..31, with default 17. Subnet will be 172.<BASE+CLUSTER_ID>.0.0/16.

Single cluster, no settings needed, get 172.17.0.0/16.
Single cluster that needs special subnet, set NAT64_V4_SUBNET_BASE=20, for example.

Multicluster: can override base, if needed. CLUSTER_ID must be 0..(31-base), so that it stays within limits of private network.

Advantages: Don’t need to specify, unless have a docker issue. Maybe easier specification.
Disadvantages: CLUSTER_ID must be in a specific range. Doesn't allow use of 10.x.

Variation: Allow prefix to specify first octet, which makes this effectively the same as option B, only more complicated, by specifying two items. Subnet would be <PREFIX>.<BASE+CLUSTER_ID>.0.0/16.

**Comment by pmichali** [comment]
Working up a solution for this issue, should be posted today.
