### ISSUE TITLE
dind-cluster-v1.13.sh and dind-cluster-v1.10.sh up failed on windows 10

### ISSUE THREAD

**Issue by nasseur** [kubernetes-sigs/kubeadm-dind-cluster#276]
I'm trying to use the kubeadm-dind-cluster on Windows 10 but i'm not able to start it.
I'm getting the below error when launching the command: ./dind-cluster-v1.13.sh up

 Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"C:/Program Files/Git/usr/bin/ba                                                             sh\": stat C:/Program Files/Git/usr/bin/bash: no such file or directory": unknown.
./dind-cluster-v1.13.sh: line 790: KUBECTL_LINUX_SHA1: unbound variable

**Comment by jamesmstone** [comment]
I'm getting the same issue... But using Alpine Linux.
```
$ ./dind-cluster-v1.13.sh up
WARNING: No swap limit support
WARNING: No swap limit support
WARNING: No swap limit support
WARNING: No swap limit support
* Making sure DIND image is up to date 
sha256:0fcb655948a1fa20f5a2100983755edc8f0d763248bda217b3454d82d5cd3be4: Pulling from mirantis/kubeadm-dind-cluster
Digest: sha256:0fcb655948a1fa20f5a2100983755edc8f0d763248bda217b3454d82d5cd3be4
Status: Image is up to date for mirantis/kubeadm-dind-cluster@sha256:0fcb655948a1fa20f5a2100983755edc8f0d763248bda217b3454d82d5cd3be4
docker: Error response from daemon: failed to create endpoint modest_kepler on network bridge: failed to add the host (vethb616424) <=> sandbox (veth601a2fb) pair interfaces: operation not supported.
ERRO[0000] error waiting for container: context canceled 
./dind-cluster-v1.13.sh: line 789: KUBECTL_LINUX_SHA1: unbound variable

```

**Comment by SteveParson** [comment]
I have a related issue. I believe that the parser for the image name needs to be reworked. 
`$ ./dind-cluster-v1.13.sh up
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No memory limit support
WARNING: No swap limit support
* Making sure DIND image is up to date
FATA[0000] Invalid repository name (kubeadm-dind-cluster:596f7d093470c1dc3a3e4466bcdfb34438a99b90-v1.13), only [a-z0-9-_.] are allowed`

Examining further, it turns out that the env variable DIND_IMAGE becomes `mirantis/kubeadm-dind-cluster:596f7d093470c1dc3a3e4466bcdfb34438a99b90-v1.13@sha256:0fcb655948a1fa20f5a2100983755edc8f0d763248bda217b3454d82d5cd3be4`

As a quick workaround, you can change the lines around 2286 to the following
` 
if [[ ! ( ${DIND_IMAGE} =~ local ) && ! ${DIND_SKIP_PULL:-} ]]; then
  dind::step "Making sure DIND image is up to date"
  DIND_IMAGE=`echo ${DIND_IMAGE} | cut -f1 -d"@"`
  docker pull "${DIND_IMAGE}" >&2
fi
`
